### ISSUE TITLE
languages

### ISSUE THREAD

**Issue by eunaumtenhoid** [oxpus/Download-32-Extension#12]
**languages**
I don't know if it's on purpose, but I'm translating the ext and I realized that you use several strings of repeated languages ​​or some already have in PHPBB and you created it anyway, as I'm messing with it at the moment if you want I can report and / or make a fork

could separate the language files for common, acp, mcp and ucp it would be easier to organize and translate

**category link**
I do not know if it is possible, but everywhere that the download category shows with the link it shows as category and subcategory? for example, in the search it shows only the category that is being downloaded, it would be legal to show the 2 categories (category and subcategory); category >> subcategory

![sub](https://user-images.githubusercontent.com/22734333/82674921-5f4a2980-9c1a-11ea-82e5-2cffc0ae555c.png)
![CAT](https://user-images.githubusercontent.com/22734333/82674934-64a77400-9c1a-11ea-9e9d-8787a042729c.png)

**Downloads search results for user**
shows the name of the user in the search would be very cool, when accessing the search link for uploads of that user with the words something like this:
uploads of USER NAME

![user](https://user-images.githubusercontent.com/22734333/82152024-0d2d9080-9835-11ea-8fb5-6df3b6b73aa2.jpg)

do any of the mention extensions work in the comments or might work in the future?
is it possible to convert forum posts to comments? or is it too complicated?

no more I found no error so far

**Comment by oxpus** [comment]
The language strings are used seperated by the mod because a lot ot then doesn't exists while the extension was release the first time on the old phpBB 2.0.x. So I'll keep then in place to be sure to translate each used token.

The defining of the complete category path in the last downloads row may cause a lot of overhead and overload data so this request must be denied.

And the search for the user downloads:
It's the same result as you search within the extensions search function for an user. I've no intensions to create many more headlines for each new function which are basically the same.

At least the comments:
No, there will definitely be no further functions for the comment function.
These are not meant to be used for discussions, but rather to leave a few words for a download. Otherwise, the forum itself can be used, evel the admin enable this, to create topics for each download to provide the basis for discussions.

no more I found no error so far
> Puh, great.
