### ISSUE TITLE
more Details

### ISSUE THREAD

**Issue by eunaumtenhoid** [oxpus/Download-32-Extension#9]
the following additions are possible:

**General**
- Add preview on upload page
- Addon to use with the advanced points system for users to earn x points when creating uploads and / or comments
- the user who uploaded it can see and edit the upload before it is approved? as it currently happens in PHPBB posts.
- add a time limit for the user to be able to edit their download, after that time only adm or moderator (or a specific group) could edit the download

 **upload file**
is it possible to remove the obligation to upload a file in order to create the download?

**User defined fields**
- Is it possible to pull some information regarding the field and put it in another download area? like in front or behind the title?
- add more field type options; like checkbox, link, image
- add option to add an icon (fontawesome) in front of the field that will be displayed in the downlaod area (being configured via ACP)
- Is it possible to put an option for certain fields not to appear in certain categories?
- Is it possible to add an option so that in certain fields a standard text appears before or after the value of the field to be placed by the user? example time in this case the user only places the numbers q symbolizes the time in minutes, but in the display of the value it will show the time in numbers and soon after the word minutes (this would have been placed as a standard in the ACP to be shown right after the number which was the value placed by the user)
- add a way to further customize the final result of the values ​​displayed in the fields? with a different color, an image, or a button?
![TES](https://user-images.githubusercontent.com/22734333/81471443-8985fb00-91c7-11ea-9bf5-35e307915bce.jpg)

**Download descriptions**
this option >> Limit the Download descriptions on Index: there could be an option to completely download the description in the categories, because even if I put the number 1 it shows the description

**UCP profile**
- could be add in the user's profile number of comments he made in the donwload similar to the posts
- add in the profile the number of uploads made by the user and with a link listing all these uploads

**UCP**
- it could be add a new option in the downloads tab "my downloads" showing all the ugly downloads by himself and thus making it easier to edit and manage them

**Comments**
- add option to report a comment
- add option to quote a comment

**general notification**
do you intend to integrate the notification system with the standard phpbb notification system?

**user notification**
new notifications for users:
- when you have a new comment in the download
- when is mentioned in a comment from a download
- new comment on some download that is marked as a favorite

**manage images**

- in this image management is it possible to place it within the edit area? or make a way to make it mandatory?
- Is it possible to add a limited number of images to be added in downloads?
- what is the difference of the thumb that can be added in the edit for the images that can be add in manage images? and why does it not appear in manage images? it is possible to separate it from too many so as to put it in another download area (in this case I would like to put it as the main image of the download as a poster)

**Comment by oxpus** [comment]
**Add preview on upload page**
No. Every download can be post-processed without logging. Therefore there is no plan for a separate preview function.
**Addon to use with the advanced points system for users to earn x points when creating uploads and / or comments**
	No. The extension will not work on its own with other extensions because there is no adequate development time for the numerous other extensions. The Advanced Points system is one of them, but there are certainly countless more extensions that can be combined, which would not stop the list when starting with an extension.
**the user who uploaded it can see and edit the upload before it is approved? as it currently happens in PHPBB posts.**
	No. A download is strickly blocked for all users until it was released.
	You have to see this differentiated from a phpBB post: Attachments can also be uploaded there, but downloads are only files and links that should be published.
	How should the extension react if the uploaded files are changed while a moderator / admin is checking the download for approval?
	Regard: The file size is only limited by the PHP settings and not by phpBB options!
	The same problem is also found in phpBB posts and has been solved less happily so far.
	There is no sensible solution, so this function will not be implemented in the extension.
	Please do not forget that the download extension hosts files and by releasing the upload function to all or most users of the community, you are also given sovereignty over the management of the storage space of your own server.
**add a time limit for the user to be able to edit their download, after that time only adm or moderator (or a specific group) could edit the download**
	No. This is a very stupid option. To allow editing the own download means the user host the file on your forum. No admin or moderator should then take control of this download.

 **upload file**
	Yes, the next version will of course show the "creation" variant. After all, it's not just about uploading a file. Thanks for the hint.

**User defined fields**
	The user-defined fields were taken from the profile fields contained in phpBB and have not been further developed since phpBB 3.0.x.
	These fields should also only be used to be able to record additional information about a download without having to adapt the entire extension. Just like a user profile.
	There, these fields are no longer divided into categories or blocks, or can no longer be provided with icons.
	Therefore, even in the expansion, it is not to make any additions to the user-defined fields.
	Selection fields and "yes / no" fields are already included, but images or links are not planned. Links can be entered in each text field and images are still possible as thumbs.

**Download descriptions**
	A good idea. The next release will have a new option to enable/disable the download descriptions on the index and with separate options on search results, too.

**UCP profile**
	Number of comments okay, yes, but not linked for a list. The number of downloads linked to the search function will yes. Both will be implemented in the next release.

**UCP**
	Yes, the link to the own downloads are included the into the user profile on the next release

**Comments**
	No, comments are still public and strickly hidden until approval. To report a comment you can use the download report function.

**general notification**
	No, only the existing phpBB notification was impmenented, the remaining notifications will be still in place. There's no plan to change it.

**user notification**
	See prior point.

**manage images**
	You can feel free to change the template files as you wants to rearrange the images.
	Historically, one (the first) thumbnail has been directly integrated into the download, the other images were added later via the separate management.
	The thumbnail when downloading is sufficient in many use cases of the extension, therefore the separation of the images will not be removed in the near future.

**Comment by eunaumtenhoid** [comment]
nice, thanks for the clarifications.

**report comment**

- do you talk about the option to report a broken download? but this will disable a download if used to report a comment
- I forgot to ask, in the comments do you intend to add rank img and rank title?

**page download**
- do you want to put it on the downloads_body page to display the number of comments each download has?
- will legend icons have an option to change them via ACP?

**RELEASE OPTION**
- how can I change the option in RELEASE OPTION to set the default ** Replace the following release with the new file ** for example.
- do you want to put an option to disable the release mode as it is done with hacklist and / or TODO?

**DISPLAY EXTRA INFORMATION**
in DISPLAY EXTRA INFORMATION is it possible to change the size of the fields? I would like to add more information and / or change to text area

**UPLOADE A FILE**
it would be interesting if this button was in the PHPBB menu as is the case with the download button

**thumb**

- I looked but I saw the image of the edit function and together with the images of the mange image there is no way to change only 1 place, my idea was to do something like the custody of phpbb 1 img for poster and the rest for screenshots
![PO](https://user-images.githubusercontent.com/22734333/81501290-012e5580-92ae-11ea-88db-73cf5f5af295.jpg)
- can too many images weigh heavily on the server? an average of 7 per download?
- the question of placing a limiter of the maximum number of images that can be placed on the manage image via ACP do you think of placing?

**2 bugs**
I found 2 bugs:

- 1in rating if you vote for a download and keep clicking the vote will continue until you stop clicking, I will vote for my own 8x download (this option for us to be able to vote for the download prorpio is normal?)
![Sem título](https://user-images.githubusercontent.com/22734333/81501375-6b46fa80-92ae-11ea-8773-eec9787727bd.jpg)
- 2 in the upload numbers on the Download statistics page, after a download is changed, it continues showing the upload to the previous author, example I made 3 uploads and another user made 1 upload after I uploaded 1 upload to him, but in the statistics he continues with 1 upload and I with 3, the correct would be 2 my 2 of him.

PS: on how to check if you have a problem with my user on your site? I'm not able to log in and the email to change my password never arrives and is it possible to look to see if my email is eunaumtenhoid@outlook.com?

finally thank you very much excellent extension

**Comment by oxpus** [comment]
**report comment**
> You can select to hide or unhange the download button on reported downloads.
> And no: The comments are just simple comments. For more interaction you can use download topics.

**page downloads_body**
- do you want to put it on the downloads_body page to display the number of comments each download has?
	> No, this means an additional data overload in the extension for how many use cases?!?
- will legend icons have an option to change them via ACP?
	> No, but you can change them in the css file from the extension (colorizing) and in the fuile /dlext/controller/classes/dlext_status.php
	> The extension uses fontsome characters.
- on the download page you could have the option to show who made each upload and its date the same goes for the page Latest downloads
	> ... or you can open the statistical page to see all informations about this.

**page view_dl_body**
- how do you change or exchange the buttons; detail, comments, releases at the top of the page viewdownload
	> Feel free to edit the template files of the extension. Here the file /dlext/styles/prosilver/template/view_dl_body.html.

**RELEASE OPTION**
- how can I change the option in RELEASE OPTION to set the default ** Replace the following release with the new file ** for example.
- do you want to put an option to disable the release mode as it is done with hacklist and / or TODO?
	> You can change this in the template file /dlext/styles/prosilver/template/dl_edit_body.html.

**DISPLAY EXTRA INFORMATION**
in DISPLAY EXTRA INFORMATION is it possible to change the size of the fields? I would like to add more information and / or change to text area
> The fields for description, warning and ToDo are text fields. You can rename it as you wants in the common.php language files.
> But regard: Warning texts will be displayed per default in red and todo will be managed by the seperately todo list management.

**UPLOADE A FILE**

- it would be interesting if this button was in the PHPBB menu as is the case with the download button
	> No. There are several permissions which enable/disable this button for the current user. To check this permissions the user needs to open a download category. Like the phpBB button for a new topic.
	> And btw all buttons, positions of them and anything else will not be rearranged per default at this moment.
- this screen could be replaced by the information page, have elsewhere, but I'm not sure which
	> This form of notification has become perceptual, since all further steps are to be consciously reproduced when the form is sent. There is no "soft" error message in the upload form.

**thumb**
- I looked but I saw the image of the edit function and together with the images of the mange image there is no way to change only 1 place, my idea was to do something like the custody of phpbb 1 img for poster and the rest for screenshots
	> The images are all displayed by the same methods, i.e. as thumbnails and also as full images in the lightbox.
	> I have never understood why a single picture should deliberately be an extra preview picture ...
- can too many images weigh heavily on the server? an average of 7 per download?
	> That depends on the capacity of the server and the webserver and their utilization. This cannot be generalized. In theory, there is no loss of performance when you uses a lot of images on each download, so there are no limits to this.
- the question of placing a limiter of the maximum number of images that can be placed on the manage image via ACP do you think of placing?
	> No, the limit is here set by the server so the extension will not have any option for this.

**bugs**
I found bugs:

- 1 in rating if you vote for a download and keep clicking the vote will continue until you stop clicking, I will vote for my own 8x download (this option for us to be able to vote for the download prorpio is normal?)
	> Okay, in this extreme case, i will install a lock so that after the first click, the next clicks will been locked until the result is loaded.
	> It's strange what ideas you can come up with ...
- 2 in the upload numbers on the Download statistics page, after a download is changed, it continues showing the upload to the previous author, example I made 3 uploads and another user made 1 upload after I uploaded 1 upload to him, but in the statistics he continues with 1 upload and I with 3, the correct would be 2 my 2 of him.
	> The statistic only shows the uploads = creation of a download, not the changes on a download. And this will not be changed, because this block is named "Uploads" and not "Changes".
- 3 when I send a comment, the comment is sent normally, but this error appears > Unable to find template "downloads_approve_comment.txt" (looked into: ). the same happens when I will make a download as a favorite, where is the option to enable and disable favottios in ACP?
	> I can't reproduce this. Maybe your forum cache is broken?
PS: on how to check if you have a problem with my user on your site? I'm not able to log in and the email to change my password never arrives and is it possible to look to see if my email is eunaumtenhoid@outlook.com?
	> I can't find a registration with this mail address...

**Comment by eunaumtenhoid** [comment]
COOL ty for reply
about registration try looking for my username >> eunaumtenhoid and if you can change the email to eunaumtenhoid@outlook.com you may be eunaumtenhoid@hotmail.com

**Comment by oxpus** [comment]
as well? how can i solve this?
> ACP > Clear Cache. But this is just a guess. I don't know why the phpBB fill not find the email templates in some cases...

**about permissions**
> "All" means the category permissions for all users inclusive guests and "group" just for selected usersgroups. So if you wants do enable views and downloads for all users you can set this permissions under "all", otherwise use "group" to set different permissions for each user group.

**Comment by oxpus** [comment]
COOL ty for reply
about registration try looking for my username >> eunaumtenhoid and if you can change the email to eunaumtenhoid@outlook.com, the current email can be eunaumtenhoid@hotmail.com
> Again: Nothing.

**Comment by eunaumtenhoid** [comment]
I got it, thanks!

I asked about the permissions because everyone has these two options >> READ COMMENTS | WRITE COMMENTS, but not in groups!

on the rating I realized that after one day they returned all votes to 0, that is, all the votes are gone

I found the system to activate / deactivate the favorites strange, this option of favorites only appears in the detailed downloads if you put the option Disable notify per email: no, is it normal anyway?

I imagine it would be easier to even find this option to activate favorites if you had to activate favorites in detailed downloads? activate favorites in detailed downloads >> yes or no

1 more bug in the acp in general configurations >> displays I disabled to not show the legend in the footter, but even so it appears

**on the mode of categories and subcategories**
I created a category and a subcategory, in the category I deactivated everything and only activated the permission to see since the users will post in the subcategory, and nothing will be posted in the main category, but even then the msg "This category does not appear contain any downloads "has it removed from the main category? that is, how and in phpbb when there is a parent category it does not show this msg when there are no topics only in the categories that are within the parent category, understand?

Display subcategories on **index**
this option can only change by UCP? it would be cool if she had it in ACP to change it and set it as a default for all users

thanks for everything, looking forward to the next versions !!

PS: about the user this is a very old email that i don't have access to and so i'm not able to recover the account and it is possible to change to >> eunaumtenhoid@outlook.com?

**Comment by oxpus** [comment]
I asked about the permissions because everyone has these two options >> READ COMMENTS | WRITE COMMENTS, but not in groups!
> Comments are not setted by groups but for all, reg. users or higher user levels.
> There's no plan to change this.

on the rating I realized that after one day they returned all votes to 0, that is, all the votes are gone
> Maybe you have changed the possible rating points e. g. from 10 to 5?
> After this the extension delete all ratings to recalculate with new ratings from this point.
> On the other hand there's no function to drop all ratings.

I found the system to activate / deactivate the favorites strange, this option of favorites only appears in the detailed downloads if you put the option Disable notify per email: no, is it normal anyway?
> Yes. Favorites are used to be notified on changes on the downloads. So only when emails for notifications are enabled user can use the favorite functions, too.

I imagine it would be easier to even find this option to activate favorites if you had to activate favorites in detailed downloads? activate favorites in detailed downloads >> yes or no
> No, the intention was another one.

1 more bug in the acp in general configurations >> displays I disabled to not show the legend in the footter, but even so it appears
> The legend is hidden if you disable this. But do you mean the mini stats? For this take a look to the next option "Show extended statistical data in download footer:".
> There's no bug...

**on the mode of categories and subcategories**
I created a category and a subcategory, in the category I deactivated everything and only activated the permission to see since the users will post in the subcategory, and nothing will be posted in the main category, but even then the msg "This category does not appear contain any downloads "has it removed from the main category? that is, how and in phpbb when there is a parent category it does not show this msg when there are no topics only in the categories that are within the parent category, understand?
> "View" means here to view the category, not the downloads in this. There's no seperate permission to view/hide the downloads as the phpBB uses them for forums and topics.
> So to hide a category you just needs to disable the permission to view it. If a category is visible (view = yes), all users can see all contained downloads.
> It's better to disable downloads and uploads in the parent category and not disable to view it to keep it in the index tree wile all users shall see the parent category. 

Display subcategories on **index**
this option can only change by UCP? it would be cool if she had it in ACP to change it and set it as a default for all users
> No, there are no icons used to indicate parent cagegories like in the phpBB.
> So only the user should decide to display or hide the subdirectories on the index.

it would be great if the uploader and moderator / adm received a download notice reported as broken, such as email or even notification
> The admins already recieves these emails and each download moderator, too.

topic creation:
is it possible to take as information from the user defined fields and expose in the created topic? and maybe select which fields will be
> No, the topic already includes the link to the download to show all contents. Rather, the topic only contain the essentials and not every field from the download. Therefore the content of the topic will not be further extended.

PS: about the user this is a very old email that i don't have access to and so i'm not able to recover the account and it is possible to change to >> eunaumtenhoid@outlook.com?
> Use the password reset function...

**Comment by eunaumtenhoid** [comment]
HOW TO add multiple external links and file releases at once? so that I don’t need to edit the download several times, if I go to put 10 releases, like putting a button + there every time I click the button a new field appears to put an external link and file release

![EXTERNAL](https://user-images.githubusercontent.com/22734333/82054857-f997f380-9695-11ea-9d48-23d72b7092a2.jpg)

**Comment by oxpus** [comment]
There's only one possible link to an external download page or URL, not multiple ones.
The extension will not provide more than one external link per download only per release management on the extension be adding a new download release.

To delete the file size for external links in the upload/edit formular just hide the html element (change the element from type="text" to type="hidden").
The extension uses the file size for each download to display it on the detail page on external downloads, so this value needs to be at least 0.

**Comment by eunaumtenhoid** [comment]
perfect ty, only an idea in downloads stats could be add latest comments and number of comments there in the bot (showing the users who commented most on downloads) like the download number and upload number.

**Comment by oxpus** [comment]
No, comments will not be included in the statistics.
The focus is on the downloads, not on the data around them.

**Comment by oxpus** [comment]
Issue closed, release 8.0.14 published.
